const int n = 24-2;
std::string files[n]=
{
"vhbb_WS_BDT_M110_ZeeHighPt_8TeV.root",
"vhbb_WS_BDT_M110_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M110_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M110_ZmmLowPt_8TeV.root",
"vhbb_WS_BDT_M115_ZeeHighPt_8TeV.root",
"vhbb_WS_BDT_M115_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M115_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M115_ZmmLowPt_8TeV.root",
"vhbb_WS_BDT_M120_ZeeHighPt_8TeV.root",
"vhbb_WS_BDT_M120_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M120_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M120_ZmmLowPt_8TeV.root",
//"vhbb_WS_BDT_M125_ZeeHighPt_8TeV.root",
//"vhbb_WS_BDT_M125_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M125_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M125_ZmmLowPt_8TeV.root",
"vhbb_WS_BDT_M130_ZeeHighPt_8TeV.root",
"vhbb_WS_BDT_M130_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M130_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M130_ZmmLowPt_8TeV.root",
"vhbb_WS_BDT_M135_ZeeHighPt_8TeV.root",
"vhbb_WS_BDT_M135_ZeeLowPt_8TeV.root",
"vhbb_WS_BDT_M135_ZmmHighPt_8TeV.root",
"vhbb_WS_BDT_M135_ZmmLowPt_8TeV.root"};
